# Site settings
title: あいむふぁいん
email: genki.sugimoto.jp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of Genki Sugimoto.
  Write what I like, when I like.
baseurl: "/jp/blog" # the subpath of your site, e.g. /blog/
url: "http://genkisugimoto.com" # the base hostname & protocol for your site
twitter_username: GenkiSugimotoJP
github_username:  Genki-S

# Build settings
markdown: kramdown
